spring:
  application:
    name: task-tracker-backend
  jwt:
    secret:
    accessTokenLifeTime: 1440 # -> 1 day | only Minutes
    refreshTokenLifeTime: 44640 # -> 31 day | only Minutes
  jpa:
    show-sql: true